<?php
/**
 * Created by PhpStorm.
 * User: Taidmin
 * Date: 2020/9/22
 * Time: 22:56
 */


namespace app\api\controller;

use app\common\lib\Time;

/**
 * 需要登录的控制器继承 AuthBase
 * Class AuthBase
 * @package app\api\controller
 */
class AuthBase extends ApiBase
{
    public $userId = 0;
    public $username = "";
    public $accessToken = "";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header('access-token');

        if(!$this->accessToken || !$this->isLogin()){
            return $this->show(config('status.not_login'),'没有登录');
        }
    }

    /**
     * 判断用户是否登录
     * @return bool
     */
    public function isLogin()
    {
        $userInfo = cache(config('redis.token_pre').$this->accessToken);

        if(!$userInfo){
            return false;
        }

        if(!empty($userInfo['id']) && !empty($userInfo['username'])){
            $this->userId = $userInfo['id'];
            $this->username = $userInfo['username'];
            return true;
        }

        return false;
    }
}